name: Publish

on:
  schedule:
  - cron: "0 0 1 * *" # See https://crontab.guru/

  push:
    branches:
      - master

permissions:
   contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v4
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Run the explorer
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: |
          pip3 install cygx1
          cygx1 explorer launch README.md

      - name: Commit changes
        run: |
          git config --local user.email "support@clivern.com"
          git config --local user.name "Todd"
          git add -A

          git commit -m "🐺 Add a new fact about our Universe"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
